name: Build and deploy ASP.Net Core app to Azure Web App - sengoku-alexandria-qa

on:
  push:
    branches:
      - Release
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release SengokuProvider.API/SengokuProvider.API.sln

      - name: dotnet publish
        run: dotnet publish SengokuProvider.API/SengokuProvider.API.sln -c Release -o ${{github.workspace}}\published

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: sengoku-alexandria-release
          path: ${{github.workspace}}\published

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: sengoku-alexandria-release
          path: ${{github.workspace}}\published
      
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sengoku-alexandria-qa'
          resource-group-name: 'Alexandria'
          package: ${{github.workspace}}\published\sengoku-alexandria-release
